<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.5.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Dominic Magirr">

  
  
  
    
  
  <meta name="description" content="Motivation I don’t understand the details of concordance in survival analysis, so I’m trying to explain it to myself.
 Probabilistic index I recently read the very nice paper On the interpretation of the hazard ratio in Cox regression by Jan De Neve and Thomas Gerds.
Suppose in the context of a clinical trial we use a Cox model to compare an experimental treatment (A=1) with a control treatment (A=0), where (for simplicity here) treatment is the only term in the model (assume the model is correct, by the way).">

  
  <link rel="alternate" hreflang="en-us" href="/post/2021-12-14-notes-on-concordance/">

  


  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/2021-12-14-notes-on-concordance/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="Dominic Magirr">
  <meta property="og:url" content="/post/2021-12-14-notes-on-concordance/">
  <meta property="og:title" content="Notes on concordance | Dominic Magirr">
  <meta property="og:description" content="Motivation I don’t understand the details of concordance in survival analysis, so I’m trying to explain it to myself.
 Probabilistic index I recently read the very nice paper On the interpretation of the hazard ratio in Cox regression by Jan De Neve and Thomas Gerds.
Suppose in the context of a clinical trial we use a Cox model to compare an experimental treatment (A=1) with a control treatment (A=0), where (for simplicity here) treatment is the only term in the model (assume the model is correct, by the way)."><meta property="og:image" content="/img/icon-192.png">
  <meta property="twitter:image" content="/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2021-12-14T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2021-12-14T15:03:20&#43;00:00">
  

  


    






  






<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/2021-12-14-notes-on-concordance/"
  },
  "headline": "Notes on concordance",
  
  "datePublished": "2021-12-14T00:00:00Z",
  "dateModified": "2021-12-14T15:03:20Z",
  
  "author": {
    "@type": "Person",
    "name": "Dominic Magirr"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Dominic Magirr",
    "logo": {
      "@type": "ImageObject",
      "url": "/img/icon-512.png"
    }
  },
  "description": "Motivation I don’t understand the details of concordance in survival analysis, so I’m trying to explain it to myself.\n Probabilistic index I recently read the very nice paper On the interpretation of the hazard ratio in Cox regression by Jan De Neve and Thomas Gerds.\nSuppose in the context of a clinical trial we use a Cox model to compare an experimental treatment (A=1) with a control treatment (A=0), where (for simplicity here) treatment is the only term in the model (assume the model is correct, by the way)."
}
</script>

  

  


  


  





  <title>Notes on concordance | Dominic Magirr</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/">Dominic Magirr</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Notes on concordance</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Dec 14, 2021
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    11 min read
  </span>
  

  
  
  

  
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>I don’t understand the details of concordance in survival analysis, so I’m trying to explain it to myself.</p>
</div>
<div id="probabilistic-index" class="section level2">
<h2>Probabilistic index</h2>
<p>I recently read the very nice paper <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/bimj.201800255">On the interpretation of the hazard ratio in Cox regression</a> by Jan De Neve and Thomas Gerds.</p>
<p>Suppose in the context of a clinical trial we use a Cox model to compare an experimental treatment (A=1) with a control treatment (A=0), where (for simplicity here) treatment is the only term in the model (assume the model is correct, by the way). Let <span class="math inline">\(\theta\)</span> denote the hazard ratio.</p>
<p>De Neve and Gerds recommend interpreting the treatment effect as a <em>probabilistic index</em>, that is, the probability that a randomly chosen patient on the experimental arm has a survival time (<span class="math inline">\(T_{1,j}\)</span>) that is longer than the survival time (<span class="math inline">\(T_{0,i}\)</span>) for a randomly chosen patient on the control arm . They show that:</p>
<p><span class="math display">\[P(T_{0,i} &lt; T_{1,j}) = \frac{1}{1 + \theta}.\]</span></p>
<p>That’s a super interesting relationship. However, they only show a proof for uncensored data. How should we interpret the probabilistic index in a trial with a maximum follow-up time and administrative right censoring (i.e. almost every trial)?</p>
<p>In their discussion, De Neve and Gerds say that we must assume proportional hazards also holds after the maximum follow up time. This suggests that when interpreting <span class="math inline">\(P(T_{0,i} &lt; T_{1,j})\)</span>, we are indeed thinking about an infinite follow-up.</p>
<p>This makes me slightly uncomfortable. We can check (to some extent) whether proportional hazards looks like a reasonable assumption for the duration of the study. Assuming it continues to hold until all patients have had their event is a bit more of a stretch. It got me wondering: does the following relationship still hold:</p>
<p><span class="math display">\[P(T_{0,i} &lt; T_{1,j} \mid \text{It&#39;s possible to know given censoring}) = \frac{1}{1 + \theta}?\]</span></p>
<p>How can I formulate that a bit more precisely? Denote the censoring times for patients <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> as <span class="math inline">\(C_{0,i}\)</span> and <span class="math inline">\(C_{1,j}\)</span> (and assume, by the way, that censoring and survival distributions are independent). In order to know for sure whether or not <span class="math inline">\(T_{0,i} &lt; T_{1,j}\)</span>, I need the minimum of <span class="math inline">\(T_{1,j}\)</span> and <span class="math inline">\(T_{0,i}\)</span> to be uncensored. Also, if the maximum of <span class="math inline">\(T_{1,j}\)</span> and <span class="math inline">\(T_{0,i}\)</span> is censored, I at least need the censoring time to come after the minimum of <span class="math inline">\(T_{1,j}\)</span> and <span class="math inline">\(T_{0,i}\)</span>. So, having picked two patients at random, in order to establish who has the better survival time I need <span class="math inline">\(\min\{T_{0,i},T_{1,j}\} &lt; \min\{C_{0,i}, C_{1,j} \}\)</span>. My question becomes: does</p>
<p><span class="math display">\[P(T_{0,i} &lt; T_{1,j} \mid \min\{T_{0,i},T_{1,j}\} &lt; \min\{C_{0,i}, C_{1,j} \} ) = \frac{1}{1 + \theta}?\]</span></p>
<p>Is the answer obvious? I have a bad feeling it might be and I’m about to do some unnecessary, tedious maths. I’ll condition on the censoring times. Let <span class="math inline">\(\tau:= \min\{C_{0,i}, C_{1,j}\}\)</span>. I’m interested in</p>
<p><span class="math display">\[
\begin{aligned}
 P(T_{0,i} &lt; T_{1,j} \mid \min\{T_{0,i},T_{1,j}\} &lt; \tau )  &amp; = P(T_{0,i} &lt; T_{1,j} \mid T_{0,i} &lt; \tau \cup T_{1,j} &lt; \tau ) \\
   &amp; = \frac{P(T_{0,i} &lt; T_{1,j} \cap T_{0,i} &lt; \tau )}{ P( T_{0,i} &lt; \tau \cup T_{1,j} &lt; \tau )} \\
\end{aligned}
\]</span></p>
<p>where I have used the fact that if <span class="math inline">\(T_{1,j} &lt; \tau\)</span> but <span class="math inline">\(T_{0,j} &gt; \tau\)</span>, then it is impossible for <span class="math inline">\(T_{0,i} &lt; T_{1,j}\)</span>. Starting with the numerator, I apply the survival distribution <span class="math inline">\(S_1\)</span> to everything:</p>
<p><span class="math display">\[
\begin{aligned}
  P(T_{0,i} &lt; T_{1,j} \cap T_{0,i} &lt; \tau )&amp; =  P(S_1(T_{0,i}) &gt; S_1(T_{1,j}) \cap S_1(T_{0,i}) &gt; S_1(\tau) )\\
   &amp;=   P(S_0(T_{0,i})^\theta &gt; S_1(T_{1,j}) \cap S_0(T_{0,i})^\theta &gt; S_1(\tau) )\\
   &amp;= P(U_0^\theta &gt; U_1 \cap U_0 &gt; u_*^{1/\theta} )
\end{aligned}
\]</span>
where I have used proportional hazards, <span class="math inline">\(S_1(t)=S_0(t)^\theta\)</span> for <span class="math inline">\(t \in (0,\tau)\)</span>, and defined <span class="math inline">\(U_0 = S_0(T_{0,i})\)</span>, <span class="math inline">\(U_1 = S_1(T_{1,i})\)</span>, and <span class="math inline">\(u_*=S_1(\tau)\)</span>. Since <span class="math inline">\(U_0\)</span> and <span class="math inline">\(U_1\)</span> are independent uniform, we have</p>
<p><span class="math display">\[
\begin{aligned}
P(U_0^\theta &gt; U_1 \cap U_0 &gt; u_*^{1/\theta} ) &amp;= \int_{u_*^{1/\theta}}^1 u_0^\theta du_0 \\
                                               &amp;= \left[  \frac{u_0^{\theta+1}}{\theta+1} \right]_{u_*^{1/\theta}}^1 \\
                                               &amp;= \frac{1 - u_*^{1+\frac{1}{\theta}}}{\theta + 1}
\end{aligned}
\]</span></p>
<p>Similarly for the denominator,
<span class="math display">\[
\begin{aligned}
 P( T_{0,i} &lt; \tau \cup T_{1,j} &lt; \tau )&amp; =  P( S_1(T_{0,i}) &gt; S_1(\tau) \cup S_1(T_{1,j}) &gt; S_1(\tau) )\\
   &amp;=   P( S_0(T_{0,i})^{\theta} &gt; S_1(\tau) \cup S_1(T_{1,j}) &gt; S_1(\tau) ) \\
   &amp;=   P( U_0 &gt; u_*^{1/\theta} \cup U_1 &gt; u_* )\\
   &amp;= 1 -  P( U_0 &lt; u_*^{1/\theta} \cap U_1 &lt; u_* ) \\
   &amp;= 1 - u_*^{1+\frac{1}{\theta}},
\end{aligned}
\]</span>
and dividing the numerator by the denominator finally gives the result that
<span class="math display">\[
P(T_{0,i} &lt; T_{1,j} \mid \min\{T_{0,i},T_{1,j}\} &lt; \min\{C_{0,i}, C_{1,j} \} ) = \frac{1}{1 + \theta}.
\]</span>
Maybe this was overkill. But it’s settled my mind a little. If someone tells me that the probabilistic index is <span class="math inline">\(\phi=1/(1+\theta)\)</span> (in the context of a proportional hazards model applied to a particular trial with administrative censoring), then I can imagine repeatedly selecting two patients at random, one from each arm. Out of the pairs where it is possible to establish who has better survival, the fraction of times that it is the patient from the experimental arm is <span class="math inline">\(\phi\)</span>.</p>
<p>[As an aside, I much prefer the interpretation <span class="math inline">\(S_1(t)=S_0(t)^\theta\)</span> as <em>the interpretation</em> of the hazard ratio. Looking at the above derivation, this is the more fundamental relationship. But, then again, there are several interpretations of the hazard ratio, each with pros and cons…would need a separate post.]</p>
</div>
<div id="link-with-concordance" class="section level2">
<h2>Link with concordance</h2>
<p>I can try to show an example using the <code>concordance()</code> function from <code>R</code>’s <code>survival</code> package. Firstly, I set up a data frame with some exponentially distributed survival data from a clinical trial. The control arm median is 12 months. The experimental arm median is 18 months. Recruitment is uniform over 12 months. The sample size of 5000 per arm is deliberately oversized for illustration purposes (so the point estimate of the hazard ratio is close to 0.66).</p>
<pre class="r"><code>library(dplyr)
library(survival)

set.seed(325)

df_ex &lt;- data.frame(rec = runif(10000, 0, 12),
                    y_star = c(rexp(5000, rate = log(2) / 12),
                               rexp(5000, rate = log(2) / 18)),
                    delta_star = 1,
                    trt = rep(c(&quot;0&quot;, &quot;1&quot;), each = 5000)) %&gt;% 
   mutate(delta = as.numeric(y_star + rec &lt; 18),
          y = pmin(y_star, 18 - rec))

head(df_ex)</code></pre>
<pre><code>##         rec    y_star delta_star trt delta         y
## 1 3.4275172 15.893085          1   0     0 14.572483
## 2 9.3391460  8.595456          1   0     1  8.595456
## 3 2.1307085  9.754036          1   0     1  9.754036
## 4 2.1295279  8.575436          1   0     1  8.575436
## 5 0.6061914  4.822211          1   0     1  4.822211
## 6 6.3240452  4.126706          1   0     1  4.126706</code></pre>
<p>The data frame contains two versions of the data set. <code>(y_star, delta_star)</code> is the survival time and event status (1=event; 0=censored) for the uncensored data set, assuming an infinite follow-up time. <code>(y, delta)</code> is the survival time and event status, assuming administrative censoring 18 months after the start of the study. I can quickly plot (without tidying up axis labels etc) the Kaplan Meier estimates for the two data sets:</p>
<pre class="r"><code>fit_inf &lt;- survfit(Surv(y_star, delta_star) ~ trt, data = df_ex)
fit_18 &lt;- survfit(Surv(y, delta) ~ trt, data = df_ex)

plot(fit_inf, col = 1:2)</code></pre>
<p><img src="/post/2021-12-14-notes-on-concordance_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>plot(fit_18, col = 1:2)</code></pre>
<p><img src="/post/2021-12-14-notes-on-concordance_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<p>I’ll start with the infinite follow-up data set, and fit a Cox model to confirm that the hazard ratio is essentially 0.66…</p>
<pre class="r"><code>cph_inf &lt;- coxph(Surv(y_star, delta_star) ~ trt, data = df_ex)
summary(cph_inf)$coef</code></pre>
<pre><code>##            coef exp(coef)   se(coef)         z     Pr(&gt;|z|)
## trt1 -0.4197819 0.6571902 0.02043946 -20.53781 9.891931e-94</code></pre>
<p>I could then estimate the <em>probabilistic index</em> as <span class="math inline">\(1/(1+0.66)= 0.6\)</span>.</p>
<p>Next I calculate the <em>concordance</em>…</p>
<pre class="r"><code>con_inf &lt;- concordance(cph_inf)
con_inf</code></pre>
<pre><code>## Call:
## concordance.coxph(object = cph_inf)
## 
## n= 10000 
## Concordance= 0.5505 se= 0.002813
## concordant discordant     tied.x     tied.y    tied.xy 
##   15025449    9974551   24995000          0          0</code></pre>
<p>We see that the concordance is 0.55. So <em>concordance</em> is not the same as the <em>probabilistic index</em>.</p>
<div id="what-is-concordance" class="section level3">
<h3>What is concordance?</h3>
<p>See <a href="https://cran.r-project.org/web/packages/survival/vignettes/concordance.pdf">this nice vignette</a> by Thernau &amp; Atkinson. The motivation for concordance usually comes from evaluating the performance of a risk prediction model, rather than quantifying treatment effect. It was proposed in this context by Frank Harrell <a href="https://jamanetwork.com/journals/jama/article-abstract/372568">in this 1982 paper</a>. The idea is that if I randomly select two patients from the entire population, what is the probability that the model prediction agrees with reality in terms of who has the longer survival time? Loosely speaking, concordance is defined as
<span class="math display">\[
P(\hat{T}_i &lt; \hat{T}_j \mid T_{i} &lt; T_{j}), 
\]</span>
and if there were no ties, this would be the same as
<span class="math display">\[
P(T_i &lt; T_j \mid \hat{T}_i &lt; \hat{T}_j).
\]</span>
It’s just saying that, out of all possible samples of size 2 from the whole population, how often does the actual ordering of events match the predicted ordering. However, to deal with ties, the definition of concordance is typically extended to
<span class="math display">\[
\begin{align}
\text{Concordance}:&amp;=P( \hat{T}_i &lt; \hat{T}_j \mid T_i &lt; T_j, \hat{T}_i\neq \hat{T}_j)P(\hat{T}_i \neq \hat{T}_j\mid T_i \neq T_j) + \frac{1}{2}P(\hat{T}_i = \hat{T}_j \mid T_i \neq T_j),\\
\end{align}
\]</span>
or, equivalently,
<span class="math display">\[
P(T_i &lt; T_j \mid \hat{T}_i &lt; \hat{T}_j, T_i \neq T_j)P(\hat{T}_i \neq \hat{T}_j \mid T_i \neq T_j) + \frac{1}{2}P(\hat{T}_i = \hat{T}_j \mid T_i \neq T_j).
\]</span></p>
<p>This is just saying that, out of all samples of size 2 from the whole population, if we discard samples with tied events, how often can we correctly predict from the model who will have the longer survival times (where if our model gives us tied predictions then we choose randomly / are correct with probability 0.5)?</p>
<p>In our clinical trial context, and for our first simulated data set where there are no ties in <span class="math inline">\(T\)</span> and no censoring, we have
<span class="math display">\[
\begin{align}
\text{Concordance}&amp;=P(T_i &lt; T_j \mid A_i = 0, A_j = 1)P(A_i \neq A_j) + \frac{1}{2}P(A_i = A_j)\\
&amp;= \text{Probabilistic Index } \times P(A_i \neq A_j) + \frac{1}{2}P(A_i = A_j).
\end{align}
\]</span></p>
<p>Since <span class="math inline">\(P(A_i = A_j)\)</span> is just telling us the allocation ratio, the Concordance and Probabilistic Index are essentially carrying the same information about the treatment effect. The Probabilistic Index is more natural for describing a treatment effect. Concordance is more natural for describing performance of a risk prediction model.</p>
<p>Going back to our example</p>
<pre class="r"><code>con_inf</code></pre>
<pre><code>## Call:
## concordance.coxph(object = cph_inf)
## 
## n= 10000 
## Concordance= 0.5505 se= 0.002813
## concordant discordant     tied.x     tied.y    tied.xy 
##   15025449    9974551   24995000          0          0</code></pre>
<p>the <code>concordance()</code> function has helpfully provided us with the number of <code>concordant</code>, <code>discordant</code> and <code>tied.x</code> pairs. From these, we can get empirical estimates for both the probabilistic index and the concordance. The total number of pairs is <code>choose(10000,2)</code> = 49,995,000. The number of pairs where both patients are on the same treatment arm is <code>2*choose(5000,2)</code> = 24,995,000. That’s what we see in <code>tied.x</code>. We have <code>5000 * 5000</code> = 25,000,000 pairs where one patient comes from each arm. Of these, we see that 15,025,449 are concordant, meaning that the survival of the patient on the experimental arm was longer than the survival of the patient on the control arm, and the rest were discordant. So an empirical estimate for the probabilistic index is 15,025,449 / 25,000,000 = 0.60, which agrees with our theoretical result above. And the empirical estimate for the concordance is</p>
<p><span class="math display">\[
 \frac{15,025,449}{25,000,000}\times\frac{25,000,000}{49,995,000} + 0.5 \times \frac{24,995,000}{49,995,000} = 0.550514,
\]</span>
which is exactly what we see.</p>
<p>Now let’s move on to the censored data set…</p>
<pre class="r"><code>cph_18 &lt;- coxph(Surv(y, delta) ~ trt, data = df_ex)
summary(cph_18)$coef</code></pre>
<pre><code>##            coef exp(coef)   se(coef)        z     Pr(&gt;|z|)
## trt1 -0.3942244 0.6742028 0.03099125 -12.7205 4.549172e-37</code></pre>
<p>In this case everything looks the same…</p>
<pre class="r"><code>con_18 &lt;- concordance(cph_18)
con_18</code></pre>
<pre><code>## Call:
## concordance.coxph(object = cph_18)
## 
## n= 10000 
## Concordance= 0.5495 se= 0.004008
## concordant discordant     tied.x     tied.y    tied.xy 
##    9023362    6051734   14914532          0          0</code></pre>
<p>except that all pairs where it is impossible to establish for certain which patient had the longer survival time have been removed from consideration, and hence we see lower numbers of <code>concordant</code>, <code>discordant</code> and <code>tied.x</code> pairs. An empirical estimate of the probabilistic index, which remember I defined as
<span class="math display">\[P(T_{0,i} &lt; T_{1,j} \mid \text{It&#39;s possible to know given censoring})\]</span>
is <code>concordant</code> / (<code>concordant</code> + <code>discordant</code>) = 9023362 / (9023362 + 6051734) = 0.60, mathching the theoretical result.</p>
<p>For the concordance, I also need to modify the definition. Let <span class="math inline">\(E_{i,j}\)</span> denote the event “It’s possible to know which of <span class="math inline">\(T_i\)</span> and <span class="math inline">\(T_j\)</span> happens first”. Then</p>
<p><span class="math display">\[
\text{Concordance}:=P(T_i &lt; T_j \mid \hat{T}_i &lt; \hat{T}_j, T_i \neq T_j,E_{i,j})P(\hat{T}_i \neq \hat{T}_j \mid T_i \neq T_j,E_{i,j}) + \frac{1}{2}P(\hat{T}_i = \hat{T}_j \mid T_i \neq T_j,E_{i,j}).
\]</span>
I can estimate this empirically as</p>
<p><span class="math display">\[
 \frac{9023362}{9023362 + 6051734}\times\frac{9023362 + 6051734}{9023362 + 6051734 + 14914532} + 0.5 \times \frac{14914532}{9023362 + 6051734 + 14914532} = 0.5495443,
\]</span></p>
<p>which is exactly what we see.</p>
</div>
</div>
<div id="further-topics" class="section level2">
<h2>Further Topics</h2>
<p>I wanted to explain a bit more about</p>
<ul>
<li>standard errors for concordance. Both for empirical estimates. And using the reationship with the hazard ratio.</li>
<li>alternative weighted versions of concordance (see the <a href="https://cran.r-project.org/web/packages/survival/vignettes/concordance.pdf">vignette</a>)</li>
<li>a non-proportional hazards example.</li>
</ul>
<p>But I’ve run out of steam. Maybe I’ll come back to it another time.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<p>De Neve, Jan, and Thomas A. Gerds. “On the interpretation of the hazard ratio in Cox regression.” Biometrical Journal 62.3 (2020): 742-750.</p>
<p>Harrell, Frank E., et al. “Evaluating the yield of medical tests.” Jama 247.18 (1982): 2543-2546.</p>
<p>Therneau, Terry, and Elizabeth Atkinson. “1 The concordance statistic.” (2020).</p>
</div>

    </div>

    


















  






  
  
  
    
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hu3ad799765e91f69a41f3acc2fc665a63_309343_250x250_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Dominic Magirr</a></h5>
      <h6 class="card-subtitle">Medical Statistician</h6>
      <p class="card-text">Interested in the design, analysis and interpretation of clinical trials.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/dominic-magirr-87666b12b/" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.co.uk/citations?user=obri2xMAAAAJ&amp;hl=en" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/dominicmagirr" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="/files/cv.pdf" >
        <i class="ai ai-cv"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>









  
  



  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
      

      
      
    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.b59fdb6275ef5e6e2859c30582fc271a.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
