<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.5.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Dominic Magirr">

  
  
  
    
  
  <meta name="description" content="I’ve written a lot recently about non-proportional hazards in immuno-oncology. One aspect that I have unfortunately overlooked is covariate adjustment. Perhaps this is because it’s so easy to work with extracted data from published Kaplan-Meier plots, where the covariate data is not available. But we know from theoretical and empirical work that covariate adjustment can lead to big increases in power, and perhaps this is equally important or even more important than the power gains from using a weighted log-rank test to match the anticipated non-proportional hazards.">

  
  <link rel="alternate" hreflang="en-us" href="/post/adjusting-for-covariates-under-non-proportional-hazards/">

  


  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/adjusting-for-covariates-under-non-proportional-hazards/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="Dominic Magirr">
  <meta property="og:url" content="/post/adjusting-for-covariates-under-non-proportional-hazards/">
  <meta property="og:title" content="Adjusting for covariates under non-proportional hazards | Dominic Magirr">
  <meta property="og:description" content="I’ve written a lot recently about non-proportional hazards in immuno-oncology. One aspect that I have unfortunately overlooked is covariate adjustment. Perhaps this is because it’s so easy to work with extracted data from published Kaplan-Meier plots, where the covariate data is not available. But we know from theoretical and empirical work that covariate adjustment can lead to big increases in power, and perhaps this is equally important or even more important than the power gains from using a weighted log-rank test to match the anticipated non-proportional hazards."><meta property="og:image" content="/img/icon-192.png">
  <meta property="twitter:image" content="/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-09-12T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-09-12T15:09:34&#43;02:00">
  

  


    






  






<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/adjusting-for-covariates-under-non-proportional-hazards/"
  },
  "headline": "Adjusting for covariates under non-proportional hazards",
  
  "datePublished": "2020-09-12T00:00:00Z",
  "dateModified": "2020-09-12T15:09:34+02:00",
  
  "author": {
    "@type": "Person",
    "name": "Dominic Magirr"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Dominic Magirr",
    "logo": {
      "@type": "ImageObject",
      "url": "/img/icon-512.png"
    }
  },
  "description": "I’ve written a lot recently about non-proportional hazards in immuno-oncology. One aspect that I have unfortunately overlooked is covariate adjustment. Perhaps this is because it’s so easy to work with extracted data from published Kaplan-Meier plots, where the covariate data is not available. But we know from theoretical and empirical work that covariate adjustment can lead to big increases in power, and perhaps this is equally important or even more important than the power gains from using a weighted log-rank test to match the anticipated non-proportional hazards."
}
</script>

  

  


  


  





  <title>Adjusting for covariates under non-proportional hazards | Dominic Magirr</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/">Dominic Magirr</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Adjusting for covariates under non-proportional hazards</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Sep 12, 2020
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    7 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/categories/survival-analysis/">survival analysis</a>, <a href="/categories/clinical-trials/">clinical trials</a></span>
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      


<p>I’ve written a lot recently about <a href="/post/non-proportional-hazards-in-immuno-oncology-is-an-old-perspective-needed">non-proportional hazards in immuno-oncology</a>. One aspect that I have unfortunately overlooked is covariate adjustment. Perhaps this is because it’s so easy to work with <a href="/post/extract-patient-level-data-from-a-kaplan-meier-plot">extracted data from published Kaplan-Meier plots</a>, where the covariate data is not available. But we know from <a href="https://www.jstor.org/stable/2531154">theoretical</a> and <a href="https://trialsjournal.biomedcentral.com/articles/10.1186/1745-6215-15-139">empirical</a> work that covariate adjustment can lead to big increases in power, and perhaps this is equally important or even more important than the power gains from using a weighted log-rank test to match the anticipated non-proportional hazards. To investigate this, we would need access to immuno-oncology RCT data. In general this is not so easy, but fortunately there’s <a href="https://www.nature.com/articles/s41591-018-0134-3">this article</a> containing clinical data from two RCTs (OAK and POPLAR) comparing a checkpoint inhibitor (atezolizumab) versus chemotherapy.</p>
<p>Gandara, D.R., Paul, S.M., Kowanetz, M. et al. Blood-based tumor mutational burden as a predictor of clinical benefit in non-small-cell lung cancer patients treated with atezolizumab. Nat Med 24, 1441–1448 (2018). <a href="https://doi.org/10.1038/s41591-018-0134-3" class="uri">https://doi.org/10.1038/s41591-018-0134-3</a></p>
<p>A number of covariates are provided but I will focus on baseline ECOG grade, which is a performance status indicator – a “0” means fully active; a “1” means restricted in physically strenuous activity. Generally, you would expect patients with lower ECOG status to have longer survival.</p>
<p>Let’s have a look at the OAK data first…</p>
<pre class="r"><code>library(tidyverse)
library(survival)

## Here I&#39;m loading my library locally...
devtools::load_all(&quot;~/swlrt/&quot;)

## ...but can also get it from github
#devtools::install_github(&quot;dominicmagirr/swlrt&quot;)

## read in the clinical data from the OAK study
## create a new column OS.EVENT which is the opposite
## of OS.CNSR

dat_oak &lt;- readxl::read_excel(&quot;41591_2018_134_MOESM3_ESM.xlsx&quot;,
                              sheet = 3) %&gt;% 
  select(PtID, ECOGGR, OS, OS.CNSR, TRT01P) %&gt;%
  mutate(OS.EVENT = -1 * (OS.CNSR - 1))

## take a look at first few rows
head(dat_oak)</code></pre>
<pre><code>## # A tibble: 6 x 6
##    PtID ECOGGR    OS OS.CNSR TRT01P    OS.EVENT
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;
## 1   318      1  5.19       0 Docetaxel        1
## 2  1088      0  4.83       0 Docetaxel        1
## 3   345      1  1.94       0 Docetaxel        1
## 4   588      0 24.6        1 Docetaxel        0
## 5   306      1  5.98       0 MPDL3280A        1
## 6   718      1 19.2        1 Docetaxel        0</code></pre>
<p>It’s standard fare for surival analysis. Let’s first make a Kaplan-Meier plot and fit a Cox model based only on treatment…</p>
<pre class="r"><code>km_oak &lt;- survfit(Surv(OS, OS.EVENT) ~ TRT01P,
                  data = dat_oak)

survminer::ggsurvplot(km_oak, 
                      data = dat_oak, 
                      risk.table = TRUE, 
                      break.x.by = 6,
                      legend.title = &quot;&quot;,
                      xlab = &quot;Time (months)&quot;,
                      ylab = &quot;Overall survival&quot;,
                      risk.table.fontsize = 4,
                      legend = c(0.8,0.8))</code></pre>
<p><img src="/post/2020-09-12-adjusting-for-covariates-under-non-proportional-hazards_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>coxph(Surv(OS, OS.EVENT) ~ TRT01P, data = dat_oak)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv(OS, OS.EVENT) ~ TRT01P, data = dat_oak)
## 
##                     coef exp(coef) se(coef)      z        p
## TRT01PMPDL3280A -0.31667   0.72857  0.08418 -3.762 0.000169
## 
## Likelihood ratio test=14.16  on 1 df, p=0.0001677
## n= 850, number of events= 569</code></pre>
<p>The z-value is -3.762 (lower is better). This should be very similar to the z-value of the log-rank test. Let’s check using a function I’ve written for my own R package <a href="https://github.com/dominicmagirr/swlrt">swlrt</a>.</p>
<pre class="r"><code>swlrt::wlrt(df = dat_oak,
            trt_colname = &quot;TRT01P&quot;,
            time_colname = &quot;OS&quot;,
            event_colname = &quot;OS.EVENT&quot;,
            wlr = &quot;lr&quot;)</code></pre>
<pre><code>##           u      v_u         z o_minus_e_trt
## 1 -44.59584 139.4881 -3.775946     MPDL3280A</code></pre>
<p>Had the non-proportional hazards been anticipated, a weighted log-rank test could have been pre-specified, for example a <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/sim.8186">modestly-weighted log-rank test</a> with <span class="math inline">\(t^* = 12\)</span>…</p>
<pre class="r"><code>swlrt::wlrt(df = dat_oak,
            trt_colname = &quot;TRT01P&quot;,
            time_colname = &quot;OS&quot;,
            event_colname = &quot;OS.EVENT&quot;,
            wlr = &quot;mw&quot;,
            t_star = 12)</code></pre>
<pre><code>##           u      v_u         z o_minus_e_trt
## 1 -74.88024 370.4699 -3.890368     MPDL3280A</code></pre>
<p>This would have had a lower z-value (-3.89), as you’d expect given the slightly delayed effect,</p>
<div id="but-what-about-an-adjusted-analysis" class="section level3">
<h3>But what about an adjusted analysis?</h3>
<p>Let’s look at a Cox model including ECOG grade as a covariate…</p>
<pre class="r"><code>coxph(Surv(OS, OS.EVENT) ~ TRT01P + ECOGGR, data = dat_oak)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv(OS, OS.EVENT) ~ TRT01P + ECOGGR, data = dat_oak)
## 
##                     coef exp(coef) se(coef)      z        p
## TRT01PMPDL3280A -0.35234   0.70304  0.08445 -4.172 3.02e-05
## ECOGGR           0.63227   1.88187  0.09072  6.970 3.18e-12
## 
## Likelihood ratio test=65.79  on 2 df, p=5.163e-15
## n= 850, number of events= 569</code></pre>
<p>Now the z-value is -4.172. So in this example, remembering to adjust for a prognostic covariate appears more important than dealing with the nph issue.</p>
</div>
<div id="cant-we-do-both" class="section level3">
<h3>Can’t we do both?</h3>
<p>Yes, it’s possible to do the modestly-weighted log-rank test, stratified by ECOG grade:</p>
<pre class="r"><code>swlrt::swlrt(df = dat_oak,
             trt_colname = &quot;TRT01P&quot;,
             time_colname = &quot;OS&quot;,
             event_colname = &quot;OS.EVENT&quot;,
             strat_colname = &quot;ECOGGR&quot;,
             wlr = &quot;mw&quot;,
             t_star = 12)</code></pre>
<pre><code>## $by_strata
##                 u       v_u         z o_minus_e_trt
## ECOGGR0 -15.46822  87.47411 -1.653867     MPDL3280A
## ECOGGR1 -71.10216 307.90543 -4.052044     MPDL3280A
## 
## $z
## [1] -4.353737</code></pre>
<p>Now the z-value is lower still (-4.35), which seems like the best of both worlds.</p>
</div>
<div id="will-covariate-adjustment-always-improve-the-z-value" class="section level3">
<h3>Will covariate adjustment always improve the z-value?</h3>
<p>No. Let’s go through exactly the same steps for the POPLAR study.</p>
<pre class="r"><code>## read in the clinical data from the POPLAR study
## create a new column OS.EVENT which is the opposite
## of OS.CNSR
dat_poplar &lt;- readxl::read_excel(&quot;41591_2018_134_MOESM3_ESM.xlsx&quot;,
                              sheet = 2) %&gt;% 
  select(PtID, ECOGGR, OS, OS.CNSR, TRT01P) %&gt;%
  mutate(OS.EVENT = -1 * (OS.CNSR - 1))


km_poplar &lt;- survfit(Surv(OS, OS.EVENT) ~ TRT01P,
                  data = dat_poplar)

survminer::ggsurvplot(km_poplar, 
                      data = dat_poplar, 
                      risk.table = TRUE, 
                      break.x.by = 6,
                      legend.title = &quot;&quot;,
                      xlab = &quot;Time (months)&quot;,
                      ylab = &quot;Overall survival&quot;,
                      risk.table.fontsize = 4,
                      legend = c(0.8,0.8))</code></pre>
<p><img src="/post/2020-09-12-adjusting-for-covariates-under-non-proportional-hazards_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>coxph(Surv(OS, OS.EVENT) ~ TRT01P, data = dat_poplar)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv(OS, OS.EVENT) ~ TRT01P, data = dat_poplar)
## 
##                    coef exp(coef) se(coef)      z       p
## TRT01PMPDL3280A -0.3928    0.6752   0.1426 -2.754 0.00589
## 
## Likelihood ratio test=7.64  on 1 df, p=0.005724
## n= 287, number of events= 200</code></pre>
<pre class="r"><code>coxph(Surv(OS, OS.EVENT) ~ TRT01P + ECOGGR, data = dat_poplar)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv(OS, OS.EVENT) ~ TRT01P + ECOGGR, data = dat_poplar)
## 
##                    coef exp(coef) se(coef)      z       p
## TRT01PMPDL3280A -0.3770    0.6859   0.1426 -2.644 0.00819
## ECOGGR           0.4501    1.5684   0.1587  2.836 0.00457
## 
## Likelihood ratio test=16.18  on 2 df, p=0.000306
## n= 287, number of events= 200</code></pre>
<p>In this case the z-value from the unadjusted Cox model is -2.75, whereas adjusting for ECOGGR it’s -2.644. Let’s look at the un-stratified and stratified modestly-weighted logrank tests (<span class="math inline">\(t^* = 12\)</span>)…</p>
<pre class="r"><code>## unstratified
swlrt::wlrt(df = dat_poplar,
            trt_colname = &quot;TRT01P&quot;,
            time_colname = &quot;OS&quot;,
            event_colname = &quot;OS.EVENT&quot;,
            wlr = &quot;mw&quot;,
            t_star = 12)</code></pre>
<pre><code>##           u      v_u         z o_minus_e_trt
## 1 -36.83455 134.8164 -3.172372     MPDL3280A</code></pre>
<pre class="r"><code>## stratified
swlrt::swlrt(df = dat_poplar,
             trt_colname = &quot;TRT01P&quot;,
             time_colname = &quot;OS&quot;,
             event_colname = &quot;OS.EVENT&quot;,
             strat_colname = &quot;ECOGGR&quot;,
             wlr = &quot;mw&quot;,
             t_star = 12)</code></pre>
<pre><code>## $by_strata
##                 u       v_u         z o_minus_e_trt
## ECOGGR0 -12.98698  27.30791 -2.485215     MPDL3280A
## ECOGGR1 -20.73634 114.79982 -1.935359     MPDL3280A
## 
## $z
## [1] -2.828926</code></pre>
<p>Same pattern here, but with lower z-values, as you’d expect given the delayed effect.</p>
</div>
<div id="why-the-different-behaviour-oak-vs-poplar" class="section level3">
<h3>Why the different behaviour: OAK vs POPLAR?</h3>
<p>This is partly explained from looking at the KM curves by ECOG grade in the two studies. In OAK there is a very big difference in surival (ECOG 1 vs ECOG 0) with the median more-or-less doubling…</p>
<pre class="r"><code>km_oak_ecog &lt;- survfit(Surv(OS, OS.EVENT) ~ ECOGGR,
                       data = dat_oak)

survminer::ggsurvplot(km_oak_ecog, 
                      data = dat_oak, 
                      risk.table = TRUE, 
                      break.x.by = 6,
                      legend.title = &quot;&quot;,
                      xlab = &quot;Time (months)&quot;,
                      ylab = &quot;Overall survival&quot;,
                      risk.table.fontsize = 4,
                      legend = c(0.8,0.8))</code></pre>
<p><img src="/post/2020-09-12-adjusting-for-covariates-under-non-proportional-hazards_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>…whereas for POPLAR there is still a clear difference but median only increased by about 33%…</p>
<pre class="r"><code>km_poplar_ecog &lt;- survfit(Surv(OS, OS.EVENT) ~ ECOGGR,
                          data = dat_poplar)


survminer::ggsurvplot(km_poplar_ecog, 
                      data = dat_poplar, 
                      risk.table = TRUE, 
                      break.x.by = 6,
                      legend.title = &quot;&quot;,
                      xlab = &quot;Time (months)&quot;,
                      ylab = &quot;Overall survival&quot;,
                      risk.table.fontsize = 4,
                      legend = c(0.8,0.8))</code></pre>
<p><img src="/post/2020-09-12-adjusting-for-covariates-under-non-proportional-hazards_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="conclusions" class="section level3">
<h3>Conclusions</h3>
<p>This is just a couple of quick examples, but I think it’s safe to say that if you believe you have a strong prognostic covariate and a delayed treatment effect, then a stratified modestly-weighted logrank test is likely to be a good option in terms of type 1 error and power.</p>
<p>A lot of work has been done on covariate adjustment. Clearly, it’s a complex discussion but I think the consensus is that you are likely to gain more than you lose. A few references I’ve found useful:</p>
<p><a href="https://www.sciencedirect.com/science/article/pii/S0197245697001475" class="uri">https://www.sciencedirect.com/science/article/pii/S0197245697001475</a></p>
<p><a href="https://www.sciencedirect.com/science/article/pii/S1047279705003248" class="uri">https://www.sciencedirect.com/science/article/pii/S1047279705003248</a></p>
<p><a href="https://trialsjournal.biomedcentral.com/articles/10.1186/1745-6215-15-139" class="uri">https://trialsjournal.biomedcentral.com/articles/10.1186/1745-6215-15-139</a></p>
<p><a href="https://onlinelibrary.wiley.com/doi/full/10.1002/sim.5713" class="uri">https://onlinelibrary.wiley.com/doi/full/10.1002/sim.5713</a></p>
<p>The stratified weighted log-rank test has its limits. It can’t handle continuous covariates, and it’s going to break down when the number of strata becomes too large.</p>
</div>

    </div>

    


















  






  
  
  
    
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hu3ad799765e91f69a41f3acc2fc665a63_309343_250x250_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Dominic Magirr</a></h5>
      <h6 class="card-subtitle">Medical Statistician</h6>
      <p class="card-text">Interested in the design, analysis and interpretation of clinical trials.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/dominic-magirr-87666b12b/" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.co.uk/citations?user=obri2xMAAAAJ&amp;hl=en" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/dominicmagirr" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="/files/cv.pdf" >
        <i class="ai ai-cv"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>









  
  



  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
      

      
      
    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.01f68d44d80310e669a1731b68a35481.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
