<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.58.3" />


<title>flexsurv - Dominic Magirr</title>
<meta property="og:title" content="flexsurv - Dominic Magirr">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/dominicmagirr">GitHub</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">4 min read</span>
    

    <h1 class="article-title">flexsurv</h1>

    
    <span class="article-date">2019-10-28</span>
    

    <div class="article-content">
      


<p>I’m going to write about some of my favourite R packages. I’ll start with <code>flexsurv</code> (<a href="https://github.com/chjackson/flexsurv-dev" class="uri">https://github.com/chjackson/flexsurv-dev</a>) by Chris Jackson, which can be used to fit all kinds of parametric models to survival data. It can really do a lot, but I’ll pick out just 2 cool things I like about it:</p>
<ol style="list-style-type: decimal">
<li>Fit a standard survival model, but where it’s <em>slightly</em> easier to work out what the parameters mean.</li>
<li>Fit a proportional hazards model, which is a lot like a Cox model, but where you also model the baseline hazard using a spline.</li>
</ol>
<div id="consistent-parameter-values" class="section level2">
<h2>1. Consistent parameter values</h2>
<p>As mentioned in the tutorial (<a href="https://www.jstatsoft.org/article/view/v070i08" class="uri">https://www.jstatsoft.org/article/view/v070i08</a>), for simple models <code>flexsurvreg</code> acts as a wrapper for <code>survival::survreg</code>, but where the parameters in the output match those of <code>dweibull</code>.</p>
<p>With <code>survival::survreg</code> I would do, e.g.:</p>
<pre class="r"><code>dat_ovarian &lt;- survival::ovarian
dat_ovarian$rx &lt;- factor(dat_ovarian$rx)

library(survival)
fit_survreg = survreg(Surv(futime, fustat) ~ rx, 
                      dist = &quot;weibull&quot;,
                      data = dat_ovarian)

summary(fit_survreg)</code></pre>
<pre><code>## 
## Call:
## survreg(formula = Surv(futime, fustat) ~ rx, data = dat_ovarian, 
##     dist = &quot;weibull&quot;)
##              Value Std. Error     z      p
## (Intercept)  6.825      0.344 19.84 &lt;2e-16
## rx2          0.559      0.529  1.06   0.29
## Log(scale)  -0.121      0.251 -0.48   0.63
## 
## Scale= 0.886 
## 
## Weibull distribution
## Loglik(model)= -97.4   Loglik(intercept only)= -98
##  Chisq= 1.18 on 1 degrees of freedom, p= 0.28 
## Number of Newton-Raphson Iterations: 5 
## n= 26</code></pre>
<p>Then I would look around online for an explanation of the output e.g. (<a href="https://stats.stackexchange.com/questions/159044/weibull-survival-model-in-r" class="uri">https://stats.stackexchange.com/questions/159044/weibull-survival-model-in-r</a>). There is also an explanation in <code>?survreg</code>.</p>
<p>On the other hand, using <code>flexsurv</code>:</p>
<pre class="r"><code>library(flexsurv)
fit_flexsurvreg = flexsurvreg(Surv(futime, fustat) ~ rx, 
                              dist = &quot;weibull&quot;,
                              data = dat_ovarian)

fit_flexsurvreg</code></pre>
<pre><code>## Call:
## flexsurvreg(formula = Surv(futime, fustat) ~ rx, data = dat_ovarian, 
##     dist = &quot;weibull&quot;)
## 
## Estimates: 
##        data mean  est       L95%      U95%      se        exp(est)
## shape        NA      1.129     0.690     1.848     0.284        NA
## scale        NA    920.128   468.868  1805.704   316.508        NA
## rx2       0.500      0.559    -0.478     1.597     0.529     1.749
##        L95%      U95%    
## shape        NA        NA
## scale        NA        NA
## rx2       0.620     4.936
## 
## N = 26,  Events: 12,  Censored: 14
## Total time at risk: 15588
## Log-likelihood = -97.36415, df = 3
## AIC = 200.7283</code></pre>
<p>The parameters <code>shape</code> and <code>scale</code> correspond to <code>dweibull</code>. So I don’t have to think any further? Not quite: I still have to work out what the estimate of <code>rx2</code> is doing. I might look at <code>exp(est) = 1.749</code> and somehow expect this to be a hazard ratio. It’s not. It’s a multiplicative effect on the scale parameter. So when <code>rx = 1</code> the scale is <code>920.1</code>, and when <code>rx = 2</code> the scale is <code>920.1 * 1.749</code>. The hazard ratio (treatment 2 vs treatment 1) is</p>
<p><span class="math display">\[\begin{align} \frac{h_2(x)}{h_1(x)} &amp; = \left( \frac{b_1}{b_2} \right)^a \\
                                      &amp; = \left( \frac{920.1}{920.1 \times 1.749} \right)^{1.129}\\
                                      &amp; = 0.53 \end{align} \]</span></p>
<p>where <span class="math inline">\(a\)</span> is the common shape parameter, and <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> are the scale parameters.</p>
<p>Once I had started writing this post, I realized that it’s actually not straightforward to make inference on the hazard ratio using <code>flexsurv</code>. For working out variances/covariances, the <code>survreg</code> parameterization is indeed better. I looked around for other R packages in this space, and found <code>SurvRegCensCov</code>, which can do this conversion automatically for you:</p>
<pre class="r"><code>library(SurvRegCensCov)
ConvertWeibull(fit_survreg)$HR</code></pre>
<pre><code>##            HR        LB       UB
## rx2 0.5318051 0.1683444 1.679989</code></pre>
<p>For completeness, using <code>flexsurv</code>, the log-hazard ratio is</p>
<p><span class="math display">\[\begin{align} \log\left( \frac{h_2(x)}{h_1(x) }\right) &amp; = a\left\lbrace \log(b_1) - \log(b_2) \right\rbrace \\
                                                         &amp; = -\exp(\log(a)) \times \left\lbrace \log(b_2) - \log(b_1)  \right\rbrace \end{align}\]</span></p>
<p>I can extract the terms <span class="math inline">\(\alpha:=\log(a)\)</span> and <span class="math inline">\(\beta:=\log(b_2) - \log(b_1)\)</span> from the <code>fit_flexsurvreg</code> object, as well as their (co)variance.</p>
<pre class="r"><code>alpha &lt;- fit_flexsurvreg$res.t[&quot;shape&quot;, &quot;est&quot;]
beta &lt;- fit_flexsurvreg$res.t[&quot;rx2&quot;, &quot;est&quot;]
cov_alpha_beta &lt;- vcov(fit_flexsurvreg)[c(&quot;shape&quot;, &quot;rx2&quot;), c(&quot;shape&quot;, &quot;rx2&quot;)]</code></pre>
<p>Then work out the variance of the log-hazard ratio using the delta method.</p>
<p><span class="math display">\[\text{var}\left\lbrace -\beta\exp(\alpha) \right\rbrace = (-\beta\exp(\alpha), -\exp(\alpha)) \text{Cov}(\alpha, \beta) \left( \begin{array}{c} -\beta\exp(\alpha) \\ -\exp(\alpha) \end{array}\right)\]</span></p>
<pre class="r"><code>grad &lt;- matrix(c(-beta*exp(alpha),
                 -exp(alpha)), 
               ncol = 1)
var_lhr = t(grad) %*% cov_alpha_beta %*% grad
se_lhr = sqrt(var_lhr)
se_lhr</code></pre>
<pre><code>##           [,1]
## [1,] 0.5868807</code></pre>
<p>And to get a 95% confidence interval for the hazard ratio…</p>
<pre class="r"><code>log_hr = -exp(alpha) * beta
log_hr_upr = log_hr + qnorm(0.975) * se_lhr
log_hr_lwr = log_hr - qnorm(0.975) * se_lhr

data.frame(HR = exp(log_hr),
           LB = exp(log_hr_lwr),
           UB = exp(log_hr_upr))</code></pre>
<pre><code>##          HR        LB       UB
## 1 0.5318051 0.1683444 1.679988</code></pre>
</div>
<div id="splines" class="section level2">
<h2>Splines</h2>
<p>The second thing I really like about <code>flexsurv</code> is the proportional hazards model with a spline for the baseline hazard. I’ll explore this in <a href="/2019/11/01/flexsurv-2">another post</a>.</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

